model_name: google/gemma-3-27b-it
tokenizer_name: 
torch_dtype: bfloat16
device_map: auto
max_new_tokens: 1024
do_sample: false
temperature: 0.0
max_content_length: 12000
data: ./data/critical_cves_2016_2025.csv
